[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

# Empty project table to avoid metadata conflicts
[project]
name = "SpinStep"
version = "0.1.0"
description = "Quaternion-driven traversal framework"
requires-python = ">=3.8"
# Mark everything as dynamic to let setup.py handle it
dynamic = ["dependencies", "readme", "license", "authors"]

# Skip package discovery completely - just use what's in setup.py
[tool.setuptools.dynamic]
version = {attr = "spinStep.__version__"}
