[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SpinStep"
version = "0.1.0"
description = "A quaternion-driven traversal framework for trees and orientation-based data structures"
authors = [
    {name = "Eraldo Marques", email = "eraldo.bernardo@gmail.com"}
]
requires-python = ">=3.8"

[tool.setuptools]
packages = ["spinStep"]
