[project]
name = "spinstep"
version = "0.1.0"
description = "A quaternion-based tree traversal framework for orientation-aware data structures."
authors = [
    { name = "Your Name", email = "your@email.com" }
]
license = { text = "MIT" }  # Use this format for clarity
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "numpy>=1.22",
    "scipy>=1.8"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "flake8"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
