[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

# Most minimal configuration possible
[project]
name = "SpinStep"
version = "0.0.0"  # Placeholder version
description = "Work in progress"
requires-python = ">=3.8"

# Skip package discovery completely
[tool.setuptools]
py-modules = []  # Empty list - don't try to find any packages
